Infinite-Chess/infinitechess.org

- readme.md
- Made first paragraphs more concise
- Reordered list of planned features
> Proposed change to readme.md

- protected-owner/scripts/game/gamefile.js
- protected-owner/scripts/game/gamefileutility.js
- protected-owner/scripts/game/gui/guigameinfo.js
- protected-owner/scripts/game/insufficientmaterial.js
- protected-owner/scripts/game/wincondition.js
- views/dev.html
I am making this pull request because I do not have permissions to contribute to [PR#27](https://github.com/Infinite-Chess/infinitechess.org/pull/27). My proposal takes over the changes of that pull request one-to-one and only makes changes to the file insufficientmaterial.js. This includes extensive commenting, fixing of bugs and a brief todo list at the start.
> Draw by insufficient material: bug fixes + extra commenting of PR#27

- .github/workflows/build.yml
- build.mjs
- nodemon.json
- package-lock.json
- package.json
This is included for the restructure of the project, not the main branch.
> Added build system for minifying & autobuild using github actions

- package.json
Fixed a bug with nodemon not working on restructure branch
> Fix npm script

- src/server/middleware/middleware.js
- src/server/middleware/send404.js
- src/server/routes/root.js
Fix the frontend for the restructure branch.
> Fix frontend

- build.mjs
Sourcemaps allows to see the real code from the browser console
> Adds sourcemaps to the minified output

- src/server/routes/createaccount.js
- src/server/routes/member.js
- src/server/utility/HTMLScriptInjector.js
Fix all possible path errors (at least, i hope this is all path errors)
> Fix all path errors (i hope)

- build.mjs
- src/server/utility/HTMLScriptInjector.js
Fixed the dev version of the game... somehow
(Restructure branch)
> Fixed dev version (somehow?)

- build.mjs
Fix bug with build where sub directory weren't minified
(restructure branch)
> Fixed bug with build

- nodemon.json
- package.json
Renames `npm run run` to `npm run start`.
> Rename npm run run to npm run start

- build.mjs
- package-lock.json
- package.json
As we are now using terser, esbuild is now useless
also added back sourcemaps
(restructure branch)
> remove esbuild

- docs/COPYING.md
- docs/NAVIGATING.md
Updated the navigation guide to reflect the new structure of the project and fix broken links
> Updated Navigation guide

- src/client/css/member.css
- src/client/scripts/member.js
- src/client/views/member.html
- src/server/controllers/members.js
- src/server/controllers/removeAccountController.js
- src/server/routes/member.js
Rebase of https://github.com/Infinite-Chess/infinitechess.org/pull/37
> Account deletion

- build.mjs
- package-lock.json
- package.json
This PR fixes source maps
It also disabled the building step in dev mode
> Fixed source maps

- src/client/views/play.html
- src/server/utility/HTMLScriptInjector.js
> fixed paths for scripts moved in PR#70

- src/client/scripts/game/chess/insufficientmaterial.js
Added the following piece combinations
```
[['rooks', 1], ['knights', 1]],
[['rooks', 1], ['bishops', 1]]
```
> add more insufficient material piece combinations

- src/client/views/play.html
> New look for ingame menu button

- src/server/controllers/createaccountController.js
- src/server/controllers/members.js
- src/server/controllers/removeAccountController.js
- src/server/routes/root.js
As stated in #1. This adds a function that is ran every 24hours/`intervalForRemovalOfOldUnverifiedAccounts`.
It checks for unverified accounts for more than `maxExistenceTimeForUnverifiedAccount`ms. and removes them from the DB.
Adds:
- `removeAccountByUsername(usernameLowercase, reason)`
- `removeOldUnverifiedMembers()` Running every interval and not meant to be used by other modules
> Unverified Accounts Removal

- src/server/game/gamemanager.js
fixed missing return on line 1224 of gamemanager.js in doesGameConclusionCheckOut so now correctly returns false if player cheated self mate
> fixed missing return

- src/server/game/gamemanager.js
> Slightly Improved Game Conclusion Check

- build.mjs
- src/client/scripts/login.js
- src/client/scripts/validation.js
Added a check after page load to see if login inputs were auto filled and updates the submit button accordingly. Before, the login button was grayed out but still clickable.
Also cleans up some code.
> Added autofill compatibility to login

- src/server/controllers/members.js
> fixed getJoinDate() and getLastSeen() returning strings instead of date objects

- src/server/config/setupTranslations.js
- translation/changes.json
- translation/en-US.toml
- translation/fr-FR.toml
Adds note field to changes.json and fixes current changes.json to be valid.
> Add note field to changes.json

- docs/NAVIGATING.md
- docs/TRANSLATIONS.md
Fixed some remaining spelling and grammar issues
> cleaned up docs a bit more

- docs/NAVIGATING.md
- docs/TRANSLATIONS.md
This is a reopening of PR #107 because it got automatically merged in the process of merging PR #111 with main, with no effect. (Basically, the latter PR included the commits of the former PR in its commit history, but they were reversed in a merge process in order for the PRs to stay distinct)
> fixed spelling and style in docs

- build.mjs
- package-lock.json
- package.json
Replaces terser with much more modern and faster swc.
> Remove terser in favor of swc

- src/client/scripts/game/chess/selection.js
> Edit mode fix

- src/client/scripts/game/rendering/arrows.js
Arrows were not optimized correctly causing slowdowns on games with many organizedlines
> Fix arrow optimization

- src/client/scripts/game/chess/specialdetect.js
> improved en passant legality check

- translation/fr-FR.toml
there is an unnecessary trailing comma in the fr-FR.toml this PR removes it
> remove unnecessary comma

- build.mjs
- package-lock.json
- package.json
Integrates Lightning CSS to decrease size of CSS files and improve compatibility.
> Integrate Lightning CSS

- src/client/scripts/game/chess/variant.js
Fixes an oversight where piece that can be promoted to but where not on the board did not have correct slide lines
> Promotion fix

- src/client/scripts/game/chess/insufficientmaterial.js
Rework of insufficientmaterial.js. The previous version was very convoluted and inconvenient for extending, so I reworked it from the ground up. Now it fully supports all planned variants of the practice mode (#153).
> rework insufficientmaterial.js

- src/client/css/play.css
- src/client/scripts/game/chess/checkmatepractice.js
- src/client/scripts/game/chess/copypastegame.js
- src/client/scripts/game/chess/endgame.js
- src/client/scripts/game/chess/engine.js
- src/client/scripts/game/chess/formatconverter.js
- src/client/scripts/game/chess/game.js
- src/client/scripts/game/chess/gamefileutility.js
- src/client/scripts/game/chess/selection.js
- src/client/scripts/game/gui/guigameinfo.js
- src/client/scripts/game/gui/guipause.js
- src/client/scripts/game/gui/guipractice.js
- src/client/scripts/game/gui/guipuzzle.js
- src/client/scripts/game/gui/guititle.js
- src/client/scripts/game/input.js
- src/client/scripts/game/misc/enginegame.js
- src/client/scripts/game/rendering/arrows.js
- src/client/scripts/game/rendering/options.js
- src/client/scripts/game/rendering/perspective.js
- src/client/scripts/game/rendering/pieces.js
- src/client/scripts/game/rendering/piecesmodel.js
- src/client/views/play.ejs
- translation/en-US.toml
The goal is to introduce a new practice mode where people can practice endgames and try to beat all possible endgames in the [endgame theory table](https://docs.google.com/spreadsheets/d/14UMBn9wHz4BwGAckl4VrTFQJyzJLUw6M16dnqe-8HuU/edit?gid=0#gid=0).
Tasks:
> Practice Mode

- src/client/views/createaccount.ejs
- src/client/views/credits.ejs
- src/client/views/index.ejs
- src/client/views/login.ejs
- src/client/views/member.ejs
- src/client/views/news.ejs
- src/client/views/play.ejs
- src/client/views/termsofservice.ejs
- translation/changes.json
- translation/en-US.toml
> Add tab titles to translations

- translation/fr-FR.toml
I speak french, but it's canadian french, but in this case  it's probably fine.
> Update french translation

- src/client/views/play.ejs
- translation/changes.json
- translation/en-US.toml
- translation/es-ES.toml
- Updated Spanish and English to version 20.
- Fixed Issue #281 
- Fixed Issue #280
> Update translations to version 20

- src/client/views/components/header.ejs
- translation/changes.json
- translation/en-US.toml
> Added language support for settings dropdown

- .gitignore
- src/client/scripts/esm/game/rendering/arrows.js
- src/client/scripts/esm/game/rendering/board.js
- src/client/scripts/esm/game/rendering/highlights.js
- src/client/scripts/esm/game/rendering/legalmoveshapes.js
- src/client/scripts/esm/game/rendering/shapes.js
> Cleaned up highlights.js and the legal move shape logic

- .gitignore
- src/client/scripts/game/input.js
- src/client/scripts/game/main.js
- src/client/scripts/game/rendering/movement.js
Added momentum to the board after dragging it.
Currently only works on mouse and with the 'WASD' keys.
> Board Momentum on dragging

- src/client/scripts/esm/chess/logic/checkdetection.js
- src/client/scripts/esm/chess/logic/clock.js
- src/client/scripts/esm/chess/logic/gamefile.js
- src/client/scripts/esm/chess/variants/omega3generator.js
- src/client/scripts/esm/chess/variants/omega4generator.js
- src/client/scripts/esm/chess/variants/variant.js
- src/client/scripts/esm/game/chess/copypastegame.js
- src/client/scripts/esm/game/chess/game.js
- src/client/scripts/esm/game/chess/selection.js
- src/client/scripts/esm/game/gui/guiclock.js
- src/client/scripts/esm/game/gui/guigameinfo.js
- src/client/scripts/esm/game/misc/onlinegame.js
- src/client/scripts/esm/game/rendering/animation.js
- src/client/scripts/esm/game/rendering/area.js
- src/client/scripts/esm/game/rendering/coin.js
- src/client/scripts/esm/game/rendering/highlights.js
- src/client/scripts/esm/game/rendering/pieces.js
- src/client/scripts/esm/game/rendering/piecesmodel.js
- src/client/scripts/esm/game/rendering/voids.js
Fixes type imports broken by #315
> Fix type imports

- src/client/scripts/esm/game/gui/guiplay.js
- src/client/scripts/esm/game/gui/guititle.js
- src/client/scripts/esm/game/rendering/movement.js
- src/client/scripts/esm/game/rendering/transition.js
> Added board momentum for touchscreen.

- src/client/scripts/esm/chess/logic/gamefile.js
- src/client/scripts/esm/chess/logic/movepiece.js
- src/client/scripts/esm/chess/logic/wincondition.js
- src/client/scripts/esm/game/chess/game.js
- src/client/scripts/esm/game/rendering/board.js
- src/client/scripts/esm/game/rendering/piecesmodel.js
- src/client/scripts/esm/game/rendering/spritesheet.ts
> When rejoining game, animate last move after a short delay (and other minor changes)

- src/client/scripts/esm/chess/util/colorutil.ts
- src/client/scripts/esm/game/rendering/highlights/legalmovehighlights.ts
> Converted colorutil.js to typescript

- translation/es-ES.toml
I guess I forgot how to write in Spanish.
Cool!
> Error on es-ES.toml

- src/server/controllers/authenticationTokens/refreshTokenObject.ts
- translation/pt-BR.toml
Update the file to v.29, all changes made in changes.json
Changes.json is MISSING information:
Added "Chess on an Infinite Plane - Huygens Options by V. Reinhart.",
"Trappist-1 by V. Reinhart" lines 81-82
> Update v.29 pt-BR.toml

- src/client/scripts/esm/chess/logic/checkmate.js
- src/client/scripts/esm/chess/logic/formatconverter.js
- src/client/scripts/esm/chess/logic/insufficientmaterial.js
- src/client/scripts/esm/chess/logic/movepiece.ts
- src/client/scripts/esm/chess/util/moveutil.js
Captures were not flagged in game format or for draw calculation
> Fix capture not flagging in game format

- src/client/scripts/esm/game/chess/engines/engineCheckmatePractice.ts
(The engine thought that a huygen is blocked if there's a piece at a composite distance from it)
> Fix huygen engine bug

- src/client/scripts/esm/game/chess/game.ts
- src/client/scripts/esm/game/rendering/highlights/highlights.ts
- src/client/scripts/esm/game/rendering/highlights/specialrighthighlights.ts
Toggled by pressing 7.
Warning: will create lag if there are hundreds of thousands of pawns.
> Special rights debug option

- src/client/scripts/esm/chess/logic/insufficientmaterial.js
- src/client/scripts/esm/game/chess/checkmatepractice.ts
- src/client/scripts/esm/game/chess/engines/engineCheckmatePractice.ts
The engine is being improved, especially for the 2 hawk + bishop endgame.
> Practice Mode Engine improvements

- translation/pt-BR.toml
46 Is the Current Version
Made all the necessary changes from changes.json
> 46 Update pt-BR.toml

- src/client/scripts/esm/game/chess/copypastegame.js
- src/client/scripts/esm/game/chess/gameformulator.ts
Now we should be able to convert ICNs to gamefiles on the server side without having to import any client-side only code.
> Added ICNToGamefile() to gameformulator.ts

- translation/news/fr-FR/2024-11-22
> Create 2024-11-22 and translated it

- src/client/scripts/esm/chess/logic/boardchanges.ts
- src/client/scripts/esm/chess/logic/gamefile.js
- src/client/scripts/esm/game/chess/checkmatepractice.ts
- src/client/scripts/esm/game/chess/game.ts
- src/client/scripts/esm/game/chess/gameslot.ts
- src/client/scripts/esm/game/chess/graphicalchanges.ts
- src/client/scripts/esm/game/chess/movesequence.ts
- src/client/scripts/esm/game/chess/selection.ts
- src/client/scripts/esm/game/gui/guinavigation.ts
- src/client/scripts/esm/game/misc/controls.ts
- src/client/scripts/esm/game/misc/enginegame.ts
- src/client/scripts/esm/game/misc/onlinegame/movesendreceive.ts
- src/client/scripts/esm/game/misc/onlinegame/onlinegamerouter.ts
- src/client/scripts/esm/game/misc/onlinegame/resyncer.ts
- src/client/scripts/esm/game/rendering/piecemodels.ts
- src/client/scripts/esm/game/rendering/pieces.ts
Moves mesh information completely outside of the gamefile.
> Seperation of mesh and gamefile

- src/server/game/gamemanager/movesubmission.js
When moves desync, the server errors before it can send a resync message
> Fix resync error

- src/client/css/member.css
- src/client/views/member.ejs
> Update look of member page

- src/client/scripts/esm/game/gui/guiplay.js
- src/client/views/play.ejs
> Disable computer games in prep for 1.7 update.

- src/client/scripts/esm/chess/logic/boardchanges.ts
- src/client/scripts/esm/chess/logic/fourdimensionalmoves.ts
- src/client/scripts/esm/chess/logic/movepiece.ts
- src/client/scripts/esm/chess/logic/specialmove.ts
- src/client/scripts/esm/chess/rendering/imagecache.ts
- src/client/scripts/esm/chess/rendering/texturecache.ts
- src/client/scripts/esm/chess/util/typeutil.ts
- src/client/scripts/esm/game/chess/gameslot.ts
- src/client/scripts/esm/game/chess/graphicalchanges.ts
- src/client/scripts/esm/game/chess/movesequence.ts
- src/client/scripts/esm/game/chess/selection.ts
- src/client/scripts/esm/game/misc/enginegame.ts
- src/client/scripts/esm/game/misc/onlinegame/movesendreceive.ts
- src/client/scripts/esm/game/misc/onlinegame/resyncer.ts
- src/client/scripts/esm/game/rendering/animation.ts
- src/client/scripts/esm/game/rendering/dragging/draganimation.ts
- src/client/scripts/esm/game/rendering/miniimage.ts
- src/client/scripts/esm/game/rendering/piecemodels.ts
- src/client/scripts/esm/game/rendering/spritesheet.ts
Implement better keyframing system and animation compositor so that multiple captures can be supported in a single move
> Better capture

- src/client/scripts/esm/chess/logic/positionnormalizer/positioncompressor.ts
> Finished implementing Linear Program Model Solver
